#:kivy 1.0

<ThumbnailView>:
	BoxLayout:
		orientation: 'horizontal'
		BoxLayout:
			id: folderBox
			size_hint_x: None
			width: '200sp'
		BoxLayout:
			id: thumbnailBox
			size_hint_x: 1
			ScrollView:
				id: thumbnailScrollView
				size_hint_x: 1.0
				size_hint_y: 1.0
				do_scroll_x: False
				GridLayout:
					id: thumbnailGrid
					cols: 1		
					Button:
						text: 'Thumbnails'
						on_press: root.thumbnailClick(self)
				
				
				